### ISSUE TITLE
Question: Which time unit to use in spans?

### ISSUE THREAD

**Issue by thiamsantos** [spandex-project/spandex#125]
spandex_ecto seems to be sending to datadog the measurements in nanoseconds https://github.com/spandex-project/spandex_ecto/blob/master/lib/spandex_ecto/ecto_logger.ex#L114.

There a pattern or a preferred unit for the measurements?

**Comment by GregMefford** [comment]
According to [the Datadog API docs](https://docs.datadoghq.com/tracing/guide/send_traces_to_agent_by_api/#model), the `start` timestamp should have nanosecond granularity, and the `duration` should also have nanosecond granularity. My guess is that this is so that it's possible to represent durations like `1.25 µs`.

Note that this usage in SpandexEcto is specifically about representing the `start` and `duration` fields on each of the spans that it generates to represent the DB operation, and not the arbitrary `tags` that you might put on them or the time-series metrics you might send to Datadog using another library via the Statsd protocol. Those would be up to you to choose the granularity that you want.
